### ISSUE TITLE
Missing null check in wikidata_simplify_sparql_results

### ISSUE THREAD

**Issue by thiemowmde** [maxlath/wikidata-sdk#11]
There is a null check missing in [this line](https://github.com/maxlath/wikidata-sdk/blob/master/src/queries/wikidata_simplify_sparql_results.coffee#L39):
```coffee
switch valueObj.datatype.replace 'http://www.w3.org/2001/XMLSchema#', ''
```
The key `valueObj.datatype` is not guaranteed to be there.

@johl run into problems when using this code and I tracked the issue down a bit more.

**Comment by maxlath** [comment]
Thanks for reporting!
Do you have a query example with this case?

**Comment by thiemowmde** [comment]
Sorry, not at the moment. Maybe ask @johl?

**Comment by maxlath** [comment]
@thiemowmde @johl just published a patch, can you confirm that it work as expected?

**Comment by johl** [comment]
Works as expected. Thank you!
