### ISSUE TITLE
Add option to keep qualifiers in simplifyClaims()

### ISSUE THREAD

**Issue by larsgw** [maxlath/wikidata-sdk#12]
After `simplifyClaims()`, all qualifiers are discarded. This makes it impossible for e.g. merging P50 (author) and P2093 (author string) after fetching labels, as the P1545 (series ordinal) qualifier is gone. It would be nice to to have an option for `simplifyClaims()` or a similar method to keep these.

**Comment by maxlath** [comment]
`simplifyClaims` was first created as an attempt to get straight to the very basic facts, as that was my need at the time, but I do growingly see the need for keeping qualifiers... The issue then is that `simplifyClaims` output doesn't let much room for more complete data, you get the raw values likes
```json
{"claims": { "P279": [ "Q340169", "Q2342494", "Q386724" ] }}
```

This would require having a richer output format like
```json
{
  "claims": {
    "P279": [
      { "value": "Q340169", "qualifiers": {} },
      { "value": "Q2342494", "qualifiers": {} },
      { "value": "Q386724", "qualifiers": {} }
    ]
  }
}
```

That could make sense. PR welcome!

**Comment by egonw** [comment]
Or:

    {
      "claims": {
        "P279": {
          "Q340169": { "qualifiers": {} },
          "Q2342494"; { "qualifiers": {} },
          "Q386724"; { "qualifiers": {} }
        }
      }
    }

which is programmatically closer to the original... instead of getting the values of the list, you can now get the keys of the map, and no need to look up the .value...

**Comment by larsgw** [comment]
Well, I'm not fluent in CoffeeScript, but I'll have a go. I prefer the `{"value":...,"qualifiers":...}` idea.
