### ISSUE TITLE
pase_claim/simplify_claims dies at unknown data types

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-sdk#17]
Data type geographic shape and tabular data are not supported, so parse_claims dies on records such as <https://www.wikidata.org/wiki/Q217447>. The function should better ignore unknown data types because additional data types may be added in the future too.

**Comment by maxlath** [comment]
hello, thanks for reporting!
I think there won't be that many datatypes so we should be able to publish a patch once a new one comes out, and throwing when a datatype is unknown, while [signalling where to report it](https://github.com/maxlath/wikidata-sdk/blob/3c95db3d32092cd1d10baf5b3ce6131b8de9daea/lib/helpers/parse_claim.js#L46-L48), should help us make sure it is done. At least, I prefer this solution compared to silently fail to parse the claim and just return no value.
