### ISSUE TITLE
reduce to truthy statements

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-sdk#18]
Shoudn't simplify_claims also reduce the statements to truthy statements only?

**Comment by maxlath** [comment]
indeed, that should probably be the default behaviour, and then allow to get all the statements by passing an option

**Comment by maxlath** [comment]
that's now the default behaviour from `v5.2.4`! see the [`keepNonTruthy`](https://github.com/maxlath/wikidata-sdk/blob/master/docs/simplify_claims.md#keep-non-truthy-statements) option to disable it.

**Comment by nichtich** [comment]
Thanks, you're great! But somehow 5.2.4 did not get released at <https://www.npmjs.com/package/wikidata-sdk/>?

**Comment by maxlath** [comment]
because I forgot to `npm publish` it ^^ done!
