### ISSUE TITLE
Support simplification of special snaktypes on request

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-sdk#20]
The special values "no value" and "somevalue" are filtered out by simplification but they could also be mapped to special values such as `-` and `?` on request. I think the value `null` is best but this collides with use of `null` to skip data. The special values might help to find out which statements are complete and where information is lacking.

**Comment by maxlath** [comment]
we could have an option like `keepEmptyValues` that would return `null` for `novalue` and `somevalue`, by simply disabling the filter, but the you can't distinguish `novalue` from `somevalue`. Alternativey, those values could indeed be replaced by special values passed in options. Which way sounds the best for your use case?

**Comment by nichtich** [comment]
For my use case it would be most convenient to have two options e.g. `keepSomeValues: null` and `keepNoValue: "-"` but I am not sure if it is possible to distinguish between `null` and `undefined`. Otherwise we could introduce two constants for `novalue` and for `somevalue` so they can later be filtered out and/or mapped to custom values using the `===` operator. A function to do this filtering/mapping should be provided as part of wikidata-sdk.

**Comment by maxlath** [comment]
how about that: 9ea8a62

**Comment by nichtich** [comment]
Seems to be the most flexible and simple solution. On the other hand I'm just processing a current dump and the empty string does not occur (at least in the first 30%) so `null` and `""` are reasonable value for `novalueValue` and `somevalueValue`. With your solution `null` is no allowed value for `novalueValue` so postprocessing would be needed.

**Comment by maxlath** [comment]
we could preserve null values like so: e2242d8
