### ISSUE TITLE
Add feature: get the usage (number) of property statements

### ISSUE THREAD

**Issue by Manu1400** [maxlath/wikidata-sdk#24]
My proposal: add a good implementation (for avoid slow implementations)

i.e: `SELECT (COUNT(*) AS ?count) WHERE { [] p:P486 []. }`

https://query.wikidata.org/#%23%20number%20of%20MeSH%20ID%20%28P486%29%20statements%0A%23%20runtime%3A%20instantaneous%0ASELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20p%3AP486%20%5B%5D.%20%7D

**Comment by maxlath** [comment]
why should it be faster than `SELECT (COUNT(*) AS ?count) WHERE { ?a wdt:P486 ?b. }`?
