### ISSUE TITLE
Add support for very long BC dates on `wikidataTimeToISOString`

### ISSUE THREAD

**Issue by moshest** [maxlath/wikidata-sdk#27]
I'm not familiar with any time frame limitation for the ISO format.

I think that the method `wikidataTimeToISOString` should always return a valid ISO string even if the date if not valid of native `Date` object. This behaviour is more consistent.

For example:
```js
wdk.wikidataTimeToISOString('-13798000000-00-00T00:00:00Z')
'-13798000000-01-01T00:00:00Z'
```

**Comment by maxlath** [comment]
should be fixed by 0406b47, published in `v5.9.6`

**Comment by moshest** [comment]
Great!

You may update the docs as well:
https://github.com/maxlath/wikidata-sdk/blob/98af9ffcba406e946700601e19423e21f487977a/docs/general_helpers.md#wikidatatimetoisostring

**Comment by maxlath** [comment]
@moshest thanks for spotting!
