### ISSUE TITLE
Make utility function filterOutNonTruthyClaims public

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-sdk#35]
I need to reduce unsimplified claims to truthy claims, so method `filterOutNonTruthyClaims` should be exporter by `lib/helpers/simplify_claims.js`. I'd rename the function to `truthyClaims`, ok?

**Comment by maxlath** [comment]
added to `v5.12.0`, see [doc](https://github.com/maxlath/wikidata-sdk/blob/master/docs/general_helpers.md#truthyclaims)
