### ISSUE TITLE
Add ability to query entities by multiple property values

### ISSUE THREAD

**Issue by BynariStar** [maxlath/wikidata-sdk#37]
It would be very useful to be able to find all the entities that have one of several values for a property.

For example this query would allow you to find a list of books by their ISBN:

`const url = wdk.getReverseClaims('P212', [ '978-0-465-06710-7', '978-2-267-02700-6' ])`

Perhaps this is a round-about approach to this problem. If there is a better way I'd be happy to know!

**Comment by maxlath** [comment]
that could probably done using `UNION`s in the [SPARQL requests](https://github.com/maxlath/wikidata-sdk/blob/c6e7f0f/lib/queries/get_reverse_claims.js#L35-L51)

**Comment by BynariStar** [comment]
That's what I've figured as well, but being a SPARQL noob it'd be nice if `getReverseClaims` could handle that for me 😛

**Comment by maxlath** [comment]
done in 36d79e9 and published in `v5.15.0` :)

**Comment by BynariStar** [comment]
Amazing, thank you!

I tried it with a few property values and it works great! However, I also tried it with my specific use case (>1000 property values) and I got a timeout exception

I couldn't really find in any Wikidata documentation the max amount of `UNION`s you can do in a single query..

**Comment by maxlath** [comment]
waaaah, yes a 1000 values doesn't look doable that way ^^
could you tell me more about your case? maybe I can help you write the SPARQL query to do it without timeout

**Comment by BynariStar** [comment]
Yes.. figures :(
I have a large list of property values that should each have one wikidata item, similar to the book example with their ISBN. I need to match each value to its respective wikidata id

**Comment by maxlath** [comment]
can't you do it one by one? or, if the ensemble isn't too big, get a dump of all the values for this property against which you could match your values? For instance, you could get all the Wikidata ids matched to an ISBN-13 with [this query](https://query.wikidata.org/#SELECT%20%3Fsubject%20%3Fobject%20WHERE%20%7B%0A%20%20%3Fsubject%20wdt%3AP212%20%3Fobject%20.%0A%7D%0A)

**Comment by BynariStar** [comment]
Ah, that solution works much better :)
Thank you for your help!
