### ISSUE TITLE
add simplifyClaims support for all datatypes

### ISSUE THREAD

**Issue by maxlath** [maxlath/wikidata-sdk#4]
currently supported: `string`, `commonsMedia`, `url`, `monolingualtext`, `wikibase-item`, `time`

the complete list: `https://www.wikidata.org/wiki/Special:ListDatatypes`

most will probably just need to be added to one of the existing chain of datatypes sharing a common parser. ex: `string`, `commonsMedia` and `url`

**Comment by nichtich** [comment]
In RDF there are only three node types: bnode, uri, and literal. Wikidata data types are on another level of expression.

**Comment by nichtich** [comment]
Ok, one has to distinguish between simplification of Wikidata RDF export and simplification of Wikidata JSON export! The latter also has datatypes with different meaning than RDF datatypes.

**Comment by maxlath** [comment]
yes:
simplifyClaims -> build for the JSON api
simplifySparqlResults -> Wikidata RDF
