### ISSUE TITLE
Add option to keep novalue/somevalue on simplification

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-sdk#41]
Claim simplification maps special snaktypes `novalue` and `somevalue` to `null` and filters out these values. An option should allow to keep them as rich values e.g. `{ "snaktype": "novalue" }`. The only difficult part to implement this is deduplication at https://github.com/maxlath/wikidata-sdk/blob/e43ebdab664cb5d19802d0f438cc0ce3a91d3351/lib/helpers/simplify_claims.js#L37 but maybe deduplication should better be disabled when using this option?

**Comment by larsgw** [comment]
Am I using it wrong here? I only see one entry (instead of two) and no qualifiers:

https://runkit.com/larsgw/wdk-and-somevalue-novalue

**Comment by maxlath** [comment]
@larsgw it looks like you are still on `v5.15.9`, and not `v5.15.10` which ships the merged branch :)

**Comment by larsgw** [comment]
Oh I guess the link didn't work. On patch 10 I only see a single `'?'` in P98.

**Comment by maxlath** [comment]
[weird, I can view the updated version when visiting https://runkit.com/larsgw but not when clicking the link]

that's because you specified to replace `somevalue` by `?` in your options:
```js
claims = wdk.simplify.claims(claims, {
  keepQualifiers: true,
  somevalueValue: '?', // <---
  novalueValue: '-'
})
```
but if you specify something different (for instance `somevalueValue: { snaktype: 'somevalue' }`), you will get that something back

**Comment by larsgw** [comment]
Still no qualifiers AFAICT ([link](https://runkit.com/larsgw/wdk-and-somevalue-novalue) should work now, something about published versions vs 'master' branch).

**Comment by maxlath** [comment]
7f10ed0 adds the `keepSnaktypes` option (see [documentation](https://github.com/maxlath/wikidata-sdk/blob/master/docs/simplify_claims.md#keep-snaktypes)), that would finish to solves this issue, right? (I realized I should have asked before marking this issue as fixed and committing on master, but both could be reversed if that does't solve it)
