### ISSUE TITLE
searchEntities - searching for properties, parameter: type

### ISSUE THREAD

**Issue by LibrErli** [maxlath/wikidata-sdk#44]
Is it possible to parse wikidata for properties via wdk.searchEntities adding the parameter type:property as it is foreseen in wikidata's mediawiki api?
https://www.wikidata.org/w/api.php?action=wbsearchentities&search=alphabet&language=en&type=property

Thanks in advance!

**Comment by maxlath** [comment]
done and published in `v5.16.0`! see [documentation](https://github.com/maxlath/wikidata-sdk/blob/master/docs/search_entities.md#entities-type)
