### ISSUE TITLE
simplify.sparqlResults has multiple possible result types

### ISSUE THREAD

**Issue by EdJoPaTo** [maxlath/wikidata-sdk#45]
I would like something opposite to #40: Do not simplify sparql results as much as its currently done and generalise its output.

Simplifying the query (removing not needed variables from the select) results in a different result from `simplify.sparqlResults`.
Currently the result can be either an array of objects with the variables as keys or just an array of the single variable specified in the query.

(Whats actually worse: undefined entries in the array get lost. But when the behaviour is changed this bug will be gone too.)

When the user wants the simple array of the single variable its easy to use something like `.map(o => o.amountChildren)`. Also another simplify method could be doing that.

This would definitely be a breaking change.

Example query ([query.wikidata.org](https://query.wikidata.org/#SELECT%20DISTINCT%20%3FamountChildren%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ5.%0A%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP1971%20%3FamountChildren.%20%7D%0A%7D%0ALIMIT%205)):
```sparql
SELECT DISTINCT ?amountChildren WHERE {
  ?item wdt:P31 wd:Q5.
  OPTIONAL { ?item wdt:P1971 ?amountChildren. }
}
LIMIT 5
```

The result of the `simplify.sparqlResults` will be (something like): `[2, 6, 0, 1]`

When the query is modified to return a second variable like `?item` it will return (something like) this:

```
[
  {amountChildren: 6, item: 'Q1785'},
  {amountChildren: 2, item: 'Q2010'},
  {amountChildren: undefined, item: 'Q1747'},
  {amountChildren: undefined, item: 'Q1745'},
  {amountChildren: undefined, item: 'Q1750'}
]
```

**Comment by maxlath** [comment]
would that do the trick to have this behavior behind a flag?
```js
simplify.sparqlResults(results, { minimize: false })
```
that could maybe become the default in the future, but that would indeed be a breaking change

**Comment by EdJoPaTo** [comment]
Living without it is ok for me short term.
Long term I would like a more clean usage there.

Maybe create a staging for breaking changes or something like that so it can be just merged when a new major release is ready?

Until then the bug be fixed. `undefined` should still be in the array.

**Comment by maxlath** [comment]
what if the flag was inverted:
* `simplify.sparqlResults(results)` always returns an array of objects
* for single variable queries, `simplify.sparqlResults(results, { minimize: true })` returns an array of the values
would that work for you?

**Comment by EdJoPaTo** [comment]
I kind of like the idea but I don't think its perfect. As I tried to add typescript types (#50) I wanted to have as strict types as possible. An option determining the output of the method still has a less strict output then.

With the option as argument you depend on the input to know the output. For other languages like Java, C#, … this would require overloading the method.

I thought about having two methods for that. One with the always object array behaviour. The other one always returns simple value array and fails when it has more than one value per entry. That way the same "overloading" is there but with strictly separated names. But the "its basically the same so same method" idea is lost then.

Not sure what would be best…

**Comment by EdJoPaTo** [comment]
Looks like you went with the minimize way for 6.0.0.

I adapted #50 accordingly in d52f6b8c539afa2bf7f7f4b0e37a27f7d319652e.
