### ISSUE TITLE
install via bower can't find version 5.16.0

### ISSUE THREAD

**Issue by LibrErli** [maxlath/wikidata-sdk#46]
Tryring to install the latest version of wikidata-sdk via `bower install wikidata-sdk` results following additional error details:

`Available versions in https://github.com/maxlath/wikidata-sdk.git: 5.1.4, 5.1.3, 5.1.2, 5.1.1, 5.1.0, 5.0.0, 4.3.3, 4.3.2, 4.3.1, 4.3.0, 4.2.5, 4.2.4, 4.2.3, 4.2.2, 4.2.1, 4.2.0, 4.1.0, 4.0.6, 4.0.5, 4.0.4, 4.0.3, 4.0.2, 4.0.1, 4.0.0, 3.2.4, 3.2.3, 3.2.2, 3.2.1, 3.2.0, 3.1.0, 3.0.1, 3.0.0, 2.6.0, 2.5.0, 2.4.1, 2.4.0, 2.3.0, 2.2.2, 2.2.1, 2.2.0, 2.1.1, 2.1.0, 2.0.0, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 0.1.1, 0.1.0, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2
`

**Comment by maxlath** [comment]
fixed, I forgot to `git push --tags`
