### ISSUE TITLE
wdk.parse does not work

### ISSUE THREAD

**Issue by EdJoPaTo** [maxlath/wikidata-sdk#49]
I have no UseCase for `wdk.parse` but tried to understand its potential UseCase. It basically wants to do the same as `wdk.simplify.entities`?

But it does not work as `simplifyEntitiy` is not a function anymore. It is now an object containing `simplifyEntitiy` and `simplifyEntities`.

According to git blame this was changed 9 months ago (in https://github.com/maxlath/wikidata-sdk/commit/58caecb973e812d50f76a6e82afbcb6c4c301a20).
As I don't see someone complaining about it not working it should be removed?

Or fixed and ~moved to the Legacy part in the `index.js`~? Edit: Looks like it was meant to be in a legacy part of the `index.js`, just not obvious enough for me 😬. Maybe just one single legacy section at the end?

```
/node_modules/wikidata-sdk/lib/helpers/parse_responses.js:9
  TypeError {
    message: 'simplifyEntity is not a function',
  }
```

**Comment by maxlath** [comment]
fixing it was easier than removing it ^^

**Comment by EdJoPaTo** [comment]
But this does nearly the same as `wdk.simplify.entities` so it is a legacy method? (I don't want to remove it as its working, just want to clear things up)

What about moving all the legacy methods in `index.js` to the end in one single legacy section? Didn't realised it's a legacy method until after posting the issue.
