### ISSUE TITLE
Use wikidata sdk in an Alexa skill

### ISSUE THREAD

**Issue by Elliryc** [maxlath/wikidata-sdk#55]
Hello, I have trouble using the sdk in a skill to generate the url and simplify entities. Do you have any idea ?

**Comment by maxlath** [comment]
I'm not familiar with Alexa skill at all, but if that's running Node `>= v6.4` or some ES6 JS environment, it shouldn't be any different than other environment I guess. Can you share the problematic code and error message/stack?

**Comment by Elliryc** [comment]
Thanks, it's ok. Just a deployment problem.
