### ISSUE TITLE
unused selected variable make wdk.simplifySparqlResults crash

### ISSUE THREAD

**Issue by maxlath** [maxlath/wikidata-sdk#9]
[importing the discussion started in a wikidata-taxonomy issue](https://github.com/nichtich/wikidata-taxonomy/issues/5)

example request:
```sparql
SELECT ?item ?itemLabel ?broader ?parents
WHERE
{
    {
        SELECT ?item (count(distinct ?parent) as ?parents) {
            ?item wdt:P279* wd:Q1
            OPTIONAL { ?item wdt:P279 ?parent }
        } GROUP BY ?item
    }
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en" .
    }
}
```

result:
```json
{
  "head" : {
    "vars" : [ "item", "itemLabel", "broader", "parents" ]
  },
  "results" : {
    "bindings" : [ {
      "item" : {
        "type" : "uri",
        "value" : "http://www.wikidata.org/entity/Q1"
      },
      "parents" : {
        "datatype" : "http://www.w3.org/2001/XMLSchema#integer",
        "type" : "literal",
        "value" : "0"
      },
      "itemLabel" : {
        "xml:lang" : "en",
        "type" : "literal",
        "value" : "universe"
      }
    } ]
  }
}
```

The `broader` variable gets no result as it's not used in the `WHERE` block, thus making [parseValue](https://github.com/maxlath/wikidata-sdk/blob/cb599429f040e279911e00fcce63dbb4c5aac758/src/queries/wikidata_simplify_sparql_results.coffee#L33) crash.
@nichtich: what do you think, should the simplified result still have a `broader` key with value `null` or should the key be totally ignored?

**Comment by nichtich** [comment]
A `bnode` will be simplified as `null` so better ignore keys without values to differentiate this two cases.
